steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - .
      - '-f'
      - Dockerfile
    id: Build

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
      - '--set-secrets'
      - >
        AZURE_OPENAI_API_KEY=projects/$PROJECT_ID/secrets/AZURE_OPENAI_API_KEY:latest,
        AZURE_OPENAI_API_INSTANCE_NAME=projects/$PROJECT_ID/secrets/AZURE_OPENAI_API_INSTANCE_NAME:latest,
        AZURE_OPENAI_API_DEPLOYMENT_NAME=projects/$PROJECT_ID/secrets/AZURE_OPENAI_API_DEPLOYMENT_NAME:latest,
        AZURE_OPENAI_API_VERSION=projects/$PROJECT_ID/secrets/AZURE_OPENAI_API_VERSION:latest,
        AZURE_OPENAI_ENDPOINT=projects/$PROJECT_ID/secrets/AZURE_OPENAI_ENDPOINT:latest,
        AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_BEACH_0643A2610=projects/$PROJECT_ID/secrets/AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_BEACH_0643A2610:latest,
        CLERK_SECRET_KEY=projects/$PROJECT_ID/secrets/CLERK_SECRET_KEY:latest,
        LEMONSQUEEZY_API_KEY=projects/$PROJECT_ID/secrets/LEMONSQUEEZY_API_KEY:latest,
        MONGODB_URI=projects/$PROJECT_ID/secrets/MONGODB_URI:latest,
        OPENAI_API_KEY=projects/$PROJECT_ID/secrets/OPENAI_API_KEY:latest,
        RESEND_API_KEY=projects/$PROJECT_ID/secrets/RESEND_API_KEY:latest
      - '--update-env-vars'
      - >
        NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }},
        NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=${{ secrets.NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL }},
        NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=${{ secrets.NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL }},
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }},
        NEXT_PUBLIC_CLERK_SIGN_IN_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_IN_URL }},
        NEXT_PUBLIC_CLERK_SIGN_UP_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_UP_URL }}
    id: Deploy

images:
  - $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE_NAME: briant
  _DEPLOY_REGION: us-central1
  _TRIGGER_ID: 85b45cd9-9909-4f68-8789-f3dd0674e610
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _PLATFORM: managed

tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - briant
