export const fonts = ["DM Sans",
    "Inter",
    "Space Mono",
    "Space Grotesk",
    "Work Sans",
    "Syne",
    "Libre Franklin",
    "Cormorant",
    "Fira Sans",
    "Eczar",
    "Alegreya Sans",
    "Alegreya",
    "Source Sans Pro",
    "Source Serif Pro",
    "Roboto",
    "Fraunces",
    "Inknut Antiqua",
    "BioRhyme",
    "Poppins",
    "Archivo Narrow",
    "Libre Baskerville",
    "Playfair Display",
    "Karla",
    "Lora",
    "Proza Libre",
    "Spectral",
    "IBM Plex Sans",
    "Manrope",
    "Montserrat",
    "Lato",
    "PT Sans",
    "PT Serif",
    "Cardo",
    "Chivo",
    "Neuton",
    "Rubik",
    "Open Sans",
    "Inconsolata",
    "Raleway",
    "Merriweather",
    "Plus Jakarta Sans"
]