import type { Metadata } from "next";
import { Inter, Manrope, Urbanist } from "next/font/google";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"

// import PageLoading from "@/components/custom/PageLoading";

// const inter = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        {/* <PageLoading></PageLoading> */}
        <body>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>  
          </body>
      </html>
    </ClerkProvider>

  );
}
